name: This workflow tests other workflows!
on: 
  pull_request:
    types: [opened, reopened, synchronize]
env:
  URL: https://github.com/hatchways/team-reindeer/pull/66
  OWNER: hatchways
  REPO: team-reindeer
  PR: 66
jobs:
  collect-pr-info:
    name: Compile review keywords from PR (currently only labels and 'generic' keyword)
    runs-on: ubuntu-latest
    outputs:
          issues: ${{ steps.scrape-pr-info.outputs.issues }}
          labels: ${{ steps.scrape-pr-info.outputs.labels }}
          matrix: "{keywords: ${{ steps.scrape-pr-info.outputs.keywords }}}"
    steps:
      - uses: actions/checkout@v2
      - run: ls ./
      - id: scrape-pr-info
        name: Get linked issues and labels for related to the PR
        # env: 
        #   pr_labels: ${{ join(github.event.pull_request.labels.*.name) }}
        # run: | 
        #   echo "Scraper not yet implemented!"
        #   echo "::set-output name=matrix::{\"keyword\": [\"generic\", \"frontend\", $pr_labels]}"
        # uses: actions/hatchways/collect-pr-info@v1
        uses: ./.github/actions/pull-request-keywords
        with:
          URL: ${{ env.URL }}