name: Leave Automated Reviews
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  leave-automated-review:
    name: Leave an automated review w/ octocat/request-action
    runs-on: ubuntu-latest
    steps:
      - id: echo-pr-params
        name: Get PR Params from Github Context
        env:
          PR_OWNER: ${{ github.event.repository.owner.login }}
          PR_REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: >
          echo "New PR created in $PR_OWNER/$PR_REPO, with no: \#$PR_NUMBER. 
          Starting automatic review process for commonly present issues..."  
      - id: submit-pr
        name: Submit review w/ Github REST API
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          accept: application/vnd.github.v3+json
          event: COMMENT
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          body: |
            Congratulations on your first automated review!! &#x1F389;
          GITHUB_TOKEN: ${{ github.token }}



         

