name: Start automated review processes based on collected pull request information
on:
  workflow_call:
    inputs:
      URL:
        description: The URL of the pull request
        required: true
        type: string
      issues:
        description: |
          List of the linked issues for the pull request (should be
          obtained in the caller workflow). Use a string that will
          yield an array when parsed JSON. 
        required: false
        default: '[]'
        type: string
      labels: 
        description: |
          List of the labels for the pull request (should be
          obtained in the caller workflow). Use a string that will
          yield an array when parsed JSON.
        required: false
        default: '[]'
        type: string
      omit-generic:
        description: |
          Set to true for omitting the generic reivew
        default: false
        required: false
        type: boolean
jobs:
  checkout-and-cache-pull-request:
    name: Checkout pull request and set up packages
  # TODO: Set up caching of the dependencies here to
  #       improve review performance.
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not yet implemented!"
  initiate-automated-reviews:
    name: Call any necessary workflows that check for issues.
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix: ${{ toJSONinputs.}}
      
      fail-fast: false
      max-parallel: 10

        
